// Writes index.html: viewer.template.html with hive-model.js inlined, so the
// viewer opens straight from disk (browsers block module imports on file://).
//   node build-viewer.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const here = (f) => new URL(f, import.meta.url);
const template = readFileSync(here('./viewer.template.html'), 'utf8');
const model = readFileSync(here('./hive-model.js'), 'utf8')
  .replace(/^import \* as THREE from 'three';\n/m, '')
  .replace(/^export /gm, '');

const IMPORT = "import { buildHiveTower, PARTS } from './hive-model.js';";
if (!template.includes(IMPORT)) throw new Error('viewer.template.html no longer imports hive-model.js as expected');

// Wrap in a function so the model's top-level names stay private.
const inlined = `const { buildHiveTower, PARTS } = (() => {\n${model}\nreturn { buildHiveTower, PARTS };\n})();`;
const html = template.replace(IMPORT, () => inlined);
writeFileSync(here('./index.html'), `<!-- Generated by build-viewer.mjs from viewer.template.html + hive-model.js. Do not edit. -->\n${html}`);
console.log(`wrote index.html (${(html.length / 1024).toFixed(0)} KB)`);
