// Bundles the viewer (viewer.js + hive-model.js + three.js) into one script and
// writes the standalone page index.html, which works offline and from file://.
//
//   node build-viewer.mjs                         # index.html
//   node build-viewer.mjs --website ../../gratheon.com
//
// With --website it also copies the bundle, CSS and GLB into the gratheon.com
// repo and refreshes the embed block between the hive-tower markers in the
// robotic beehive product page.
import { build } from 'esbuild';
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const read = (f) => readFileSync(join(here, f), 'utf8');

const result = await build({
  stdin: { contents: "import { mountAll } from './viewer.js';\nmountAll();\n", resolveDir: here, loader: 'js' },
  bundle: true,
  format: 'iife',
  minify: true,
  target: 'es2020',
  write: false,
  legalComments: 'none',
});
const bundle = result.outputFiles[0].text;
const css = read('viewer.css');
const markup = read('viewer.html').trim();

// ---- standalone page ------------------------------------------------------
const page = `<!-- Generated by build-viewer.mjs from viewer.html, viewer.css, viewer.js and hive-model.js. Do not edit. -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>Hive Tower</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700&family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Sans:wght@400;500;600&display=swap">
<style>
:root { --page-bg: #eef0ec; }
@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) { --page-bg: #121512; color-scheme: dark; } }
:root[data-theme="dark"] { --page-bg: #121512; color-scheme: dark; }
html, body { height: 100%; }
body { margin: 0; background: var(--page-bg); font-family: "IBM Plex Sans", system-ui, -apple-system, "Segoe UI", sans-serif; }
.hive-tower { --ht-height: 100%; border: 0; border-radius: 0; }
${css}
</style>
${markup}
<script>${bundle.replace(/<\/script/gi, '<\\/script')}</script>
`;
writeFileSync(join(here, 'index.html'), page);
console.log(`wrote index.html (${(page.length / 1024).toFixed(0)} KB)`);

// ---- website --------------------------------------------------------------
const i = process.argv.indexOf('--website');
if (i > 0) {
  const site = resolve(process.argv[i + 1]);
  const out = (rel) => {
    const p = join(site, 'content', rel);
    mkdirSync(dirname(p), { recursive: true });
    return p;
  };
  // content/triangle/** is copied verbatim (not concatenated into main.js).
  writeFileSync(out('triangle/hive-tower/hive-tower-viewer.js'), bundle);
  writeFileSync(out('assets/css/hive-tower.css'), css);
  if (existsSync(join(here, 'hive-tower.glb'))) copyFileSync(join(here, 'hive-tower.glb'), out('assets/models/hive-tower.glb'));

  const embed = markup
    .replace(/\s*<header data-ht="header">[\s\S]*?<\/header>/, '')
    .replace('href="hive-tower.glb"', 'href="/assets/models/hive-tower.glb" download');
  const block = `<!-- hive-tower:start (generated by robotic-beehive/model/build-viewer.mjs) -->\n${embed}\n<script defer src="/assets/triangle/hive-tower/hive-tower-viewer.js"></script>\n<!-- hive-tower:end -->`;
  const pagePath = join(site, 'content/products/robotic_beehive/robotic_beehive.md');
  const md = readFileSync(pagePath, 'utf8');
  const marker = /<!-- hive-tower:start[\s\S]*?<!-- hive-tower:end -->/;
  if (!marker.test(md)) throw new Error(`${pagePath} has no <!-- hive-tower:start --> ... <!-- hive-tower:end --> block`);
  writeFileSync(pagePath, md.replace(marker, () => block));
  console.log(`updated ${site}: viewer bundle (${(bundle.length / 1024).toFixed(0)} KB), CSS, GLB, product page embed`);
}
